// Code generated by lister-gen. DO NOT EDIT.

package v1

// DeprecatedAPIRequestListerExpansion allows custom methods to be added to
// DeprecatedAPIRequestLister.
type DeprecatedAPIRequestListerExpansion interface{}

// DeprecatedAPIRequestNamespaceListerExpansion allows custom methods to be added to
// DeprecatedAPIRequestNamespaceLister.
type DeprecatedAPIRequestNamespaceListerExpansion interface{}
